# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 499344ca1abd5a4b96792a9894dd9231fee4bcd6def6e2f2907059d9f897cb8286c57e6b1e02ead2e7a577c4b735dfefd9c6c0d22cb1cb532867e76a1b68f62d

test:
  secret_key_base: bf6b0444163b57edf7356cc8917244c62c253cf76896bc4136aa0a3f98365794eb7a860e953270674be8917470ff536df98b3795d5075d9506606f65411ee9bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
